name: CI

on:
  push:
    branches: dev
  pull_request:
    branches: dev

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtest-dev

      - name: Build GoogleTest
        run: |
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Build project
        run: make

      - name: Build tests
        run: make test

      - name: Run tests
        run: ./test-shannon

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-binaries
          path: |
            shannon
            test-shannon
